local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: tagglo/site


# url: http://localhost:8081/api/v1
# allowed_hosts:
#   - localhost:8081
#   - localhost:8080
#   - localhost:3000

publish_mode: editorial_workflow

media_folder: public/img
public_folder: /img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: src/content/site/Settings.md
        label: Settings
        name: Settings
        fields:
          - { label: Site Title, name: title, widget: "string", hint: "This is the site title" }
          - { label: Login Button Text, name: loginButtonText, widget: "string", hint: "This is the login button text"  }
          - { label: SingUp Button Text, name: signUpButton, widget: "string", hint: "This is the sign up button text" }
          - { label: Meta Title, name: meta-title, widget: "string", hint: "This is the meta title"}
          - { label: Meta Description, name: meta-description, widget: "string", hint: "This is the meta description"}
          - {
              label: 'Search Engine Indexed',
              name: 'indexed',
              widget: 'boolean',
              default: true,
              hint: 'Option to disable page to be indexed, default it TRUE == Indexed ',
            }
          - { label: Footer Text, name: footerText, widget: "markdown", minimal: true, hint: "This is the footer text" }
          # - { label: Footer Term Text, name: termText, widget: "String", hint: "This is the footer Term link text" }
          # - { label: Footer Privacy Text, name: privacyText, widget: "String", hint: "This is the footer Privacy link text" }
          # - { label: Footer Consent Text, name: consentText, widget: "String", hint: "This is the footer Consent link text" }
      - file: src/content/site/Terms.md
        label: Terms
        name: Term
        fields:
          - { label: Site Title, name: title, widget: "string", hint: "This is the title" }
          - { label: Meta Title, name: meta-title, widget: "string", hint: "This is the meta title"}
          - { label: Meta Description, name: meta-description, widget: "string", hint: "This is the meta description"}
          - {
              label: 'Search Engine Indexed',
              name: 'indexed',
              widget: 'boolean',
              default: true,
              hint: 'Option to disable page to be indexed, default it TRUE == Indexed ',
            }
          - {label: "Body", name: "body", widget: "markdown", minimal: true, hint: "This is page content" }
      - file: src/content/site/Privacy.md
        label: Privacy
        name: Privacy
        fields:
          - { label: Site Title, name: title, widget: "string", hint: "This is the title" }
          - { label: Meta Title, name: meta-title, widget: "string", hint: "This is the meta title"}
          - { label: Meta Description, name: meta-description, widget: "string", hint: "This is the meta description"}
          - {
              label: 'Search Engine Indexed',
              name: 'indexed',
              widget: 'boolean',
              default: true,
              hint: 'Option to disable page to be indexed, default it TRUE == Indexed ',
            }
          - {label: "Body", name: "body", widget: "markdown", minimal: true, hint: "This is page content" }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {
        label: 'Search Engine Indexed',
        name: 'indexed',
        widget: 'boolean',
        default: true,
        hint: 'Option to disable page to be indexed, default it TRUE == Indexed ',
        }
      - {label: "Featured Image", name: "fatured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", minimal: true}  
  - name: sections
    label: Sections
    files:
      - file: src/content/sections/Hero.md
        label: Hero
        name: hero
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Button Text, name: buttonText, widget: string, hint: "This is the button text for the form" }
      - file: src/content/sections/HowItWorks.md
        label: HowItWorks
        name: howItWorks
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
      - file: src/content/sections/RequestDemo.md
        label: RequestDemo
        name: requestDemo
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - { label: Button Text, name: buttonText, widget: string, hint: "This is the button text for the form" }
      - file: src/content/sections/Features.md
        label: Features
        name: features
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - label: 'Features'
            name: 'features'
            widget: list
            summary: '{{fields.title}}'
            max: 3
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: "markdown", minimal: true }
              - { label: Image, name: image, widget: image }
      - file: src/content/sections/Benefits.md
        label: Benefits
        name: benefits
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - label: 'Benfits'
            name: 'benefits'
            widget: list
            summary: '{{fields.title}}'
            max: 6
            fields:
              - { label: Title, name: title, widget: string }
              - { label: 'Icon', name: icon, widget: 'image', }
              - { label: Description, name: description, widget: "markdown", minimal: true }
      - file: src/content/sections/Faq.md
        label: Faq
        name: faq
        fields:
          - { label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - label: 'Faqs'
            name: 'faqs'
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Answer, name: answer, widget: "markdown", minimal: true }